# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  attend-benchmarks:
    dependencies:
    - base
    - attend
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: attend is a new Haskeleton package.
executables:
  attend:
    dependencies:
    - base
    - attend
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: justanotherdot/attend
library:
  dependencies:
  - base
  - servant-server
  - wai
  - wai-app-static
  - warp
  - warp-tls
  - http-types
  source-dirs: library
license: MIT
maintainer: Ryan James Spencer <spencer.ryanjames@gmail.com>
name: attend
synopsis: A new Haskeleton package.
tests:
  attend-test-suite:
    dependencies:
    - base
    - attend
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
